pg_database: "your_pg_database"
pg_username: "your_pg_username"
pg_password: "your_pg_password"
google_client_id: "your_google_client_id"
google_client_secret: "your_google_client_secret"
hash_key: "flycat_hash_key"
hash_iv: "flycat_hash_iv"
merchant_id: "flycat_merchant_id"
return_url: "your_ngrok_return_url"
notify_url: "notify_url"
